// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoRPG.Api.Data;

#nullable disable

namespace TodoRPG.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519045816_UpdateUserAndAddRpgSystem")]
    partial class UpdateUserAndAddRpgSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TodoRPG.Api.Models.Character", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Coin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDungeonIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fortune")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("CurrentDungeonIndex");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.Dungeon", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Dungeons");

                    b.HasData(
                        new
                        {
                            Index = 1,
                            Name = "초보자의 숲",
                            RequiredCondition = 1
                        },
                        new
                        {
                            Index = 2,
                            Name = "고블린 동굴",
                            RequiredCondition = 5
                        },
                        new
                        {
                            Index = 3,
                            Name = "오크 요새",
                            RequiredCondition = 10
                        },
                        new
                        {
                            Index = 4,
                            Name = "드래곤의 둥지",
                            RequiredCondition = 20
                        });
                });

            modelBuilder.Entity("TodoRPG.Api.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsCompleted", "CreatedAt");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.Character", b =>
                {
                    b.HasOne("TodoRPG.Api.Models.Dungeon", "CurrentDungeon")
                        .WithMany()
                        .HasForeignKey("CurrentDungeonIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoRPG.Api.Models.User", "User")
                        .WithOne("Character")
                        .HasForeignKey("TodoRPG.Api.Models.Character", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentDungeon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.TodoItem", b =>
                {
                    b.HasOne("TodoRPG.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.User", b =>
                {
                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
