// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoRPG.Api.Data;

#nullable disable

namespace TodoRPG.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526135617_AddDungeonTicketsToCharacter")]
    partial class AddDungeonTicketsToCharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TodoRPG.Api.Models.Character", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Coin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDungeonIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DungeonTickets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fortune")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("CurrentDungeonIndex");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.Dungeon", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Dungeons");

                    b.HasData(
                        new
                        {
                            Index = 1,
                            Name = "초보자의 숲",
                            RequiredCondition = 1
                        },
                        new
                        {
                            Index = 2,
                            Name = "고블린 동굴",
                            RequiredCondition = 5
                        },
                        new
                        {
                            Index = 3,
                            Name = "오크 요새",
                            RequiredCondition = 10
                        },
                        new
                        {
                            Index = 4,
                            Name = "드래곤의 둥지",
                            RequiredCondition = 20
                        });
                });

            modelBuilder.Entity("TodoRPG.Api.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlusStat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlusStatValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 60,
                            Description = "가방에 군용 소총을 소지하는 것만으로 생존을 위한 강력한 완력이 솟아납니다. (근력 +10)",
                            ItemType = "NoneEquip",
                            Name = "k2소총",
                            PlusStat = "STR",
                            PlusStatValue = 10,
                            Stock = 999
                        },
                        new
                        {
                            Id = 2,
                            Cost = 150,
                            Description = "쉘터 한구석에 거대한 운동 기구를 들여놓았습니다. 보기만 해도 근육이 성장합니다. (근력 +20)",
                            ItemType = "NoneEquip",
                            Name = "스미스머신",
                            PlusStat = "STR",
                            PlusStatValue = 20,
                            Stock = 999
                        },
                        new
                        {
                            Id = 3,
                            Cost = 300,
                            Description = "[장착 장비] 최첨단 기계 수트를 몸에 걸쳐 인간의 한계를 초월한 괴력을 발휘합니다. (근력 +30)",
                            ItemType = "Equip",
                            Name = "마크42",
                            PlusStat = "STR",
                            PlusStatValue = 30,
                            Stock = 999
                        },
                        new
                        {
                            Id = 4,
                            Cost = 60,
                            Description = "[장착 장비] 방사능과 외부 독소로부터 신체를 보호하여 생존력을 높여주는 두꺼운 의류입니다. (체력 +10)",
                            ItemType = "Equip",
                            Name = "황색 방호복",
                            PlusStat = "STA",
                            PlusStatValue = 10,
                            Stock = 999
                        },
                        new
                        {
                            Id = 5,
                            Cost = 150,
                            Description = "[장착 장비] 가고일의 단단한 피부처럼 물리적 타격을 완벽히 흡수하는 석조 갑옷입니다. (체력 +20)",
                            ItemType = "Equip",
                            Name = "가고일돌갑옷",
                            PlusStat = "STA",
                            PlusStatValue = 20,
                            Stock = 999
                        },
                        new
                        {
                            Id = 6,
                            Cost = 300,
                            Description = "언제든 달릴 수 있는 유산소 기구입니다. 가방에 두는 것(?)만으로 심폐지구력이 강화됩니다. (체력 +30)",
                            ItemType = "NoneEquip",
                            Name = "런닝머신",
                            PlusStat = "STA",
                            PlusStatValue = 30,
                            Stock = 999
                        },
                        new
                        {
                            Id = 7,
                            Cost = 60,
                            Description = "인근 황무지의 지형 구조가 상세히 기록된 지도입니다. 탐색 시 판단력이 상승합니다. (지능 +10)",
                            ItemType = "NoneEquip",
                            Name = "지도",
                            PlusStat = "INT",
                            PlusStatValue = 10,
                            Stock = 999
                        },
                        new
                        {
                            Id = 8,
                            Cost = 150,
                            Description = "[장착 장비] 손목이나 장비에 연동하여 실시간으로 인공지능의 전술 연산 서포트를 받습니다. (지능 +20)",
                            ItemType = "Equip",
                            Name = "아이폰 시리",
                            PlusStat = "INT",
                            PlusStatValue = 20,
                            Stock = 999
                        },
                        new
                        {
                            Id = 9,
                            Cost = 300,
                            Description = "무너진 문명의 지식이 담긴 두꺼운 학술서입니다. 읽을 때마다 연산 능력이 깊어집니다. (지능 +30)",
                            ItemType = "NoneEquip",
                            Name = "교과서",
                            PlusStat = "INT",
                            PlusStatValue = 30,
                            Stock = 999
                        },
                        new
                        {
                            Id = 10,
                            Cost = 60,
                            Description = "종말 전 발행된 유효기간 지난 복권입니다. 왠지 모르게 좋은 일이 생길 것 같은 예감을 줍니다. (행운 +10)",
                            ItemType = "NoneEquip",
                            Name = "복권",
                            PlusStat = "LUK",
                            PlusStatValue = 10,
                            Stock = 999
                        },
                        new
                        {
                            Id = 11,
                            Cost = 150,
                            Description = "오염된 수풀 사이에서 기적적으로 발견한 돌연변이 식물입니다. 기묘한 운이 따릅니다. (행운 +20)",
                            ItemType = "NoneEquip",
                            Name = "네잎클로버",
                            PlusStat = "LUK",
                            PlusStatValue = 20,
                            Stock = 999
                        },
                        new
                        {
                            Id = 12,
                            Cost = 300,
                            Description = "[장착 장비] 이 편지는 영국에서부터 시작되었습니다... 부적처럼 몸에 품으면 불운을 막아줍니다. (행운 +30)",
                            ItemType = "Equip",
                            Name = "행운의편지",
                            PlusStat = "LUK",
                            PlusStatValue = 30,
                            Stock = 999
                        },
                        new
                        {
                            Id = 13,
                            Cost = 20,
                            Description = "위험지대로 분류된 황무지 던전에 안전하게 진입할 수 있도록 인가된 일회성 패스권",
                            ItemType = "Consume",
                            Name = "던전 입장권",
                            PlusStat = "DUN GEON",
                            PlusStatValue = 1,
                            Stock = 999
                        },
                        new
                        {
                            Id = 14,
                            Cost = 15,
                            Description = "[소모품] 마시는 즉시 단백질을 급속 충전하여 일시적으로 파괴적인 힘을 냅니다. (근력 +10)",
                            ItemType = "Consume",
                            Name = "프로틴쉐이크",
                            PlusStat = "STR",
                            PlusStatValue = 10,
                            Stock = 999
                        },
                        new
                        {
                            Id = 15,
                            Cost = 15,
                            Description = "[소모품] 심장에 주사하면 일시적으로 신체 세포가 복구되며 대사 연산 기능이 극대화됩니다. (체력 +10)",
                            ItemType = "Consume",
                            Name = "슈퍼솔져혈청",
                            PlusStat = "STA",
                            PlusStatValue = 10,
                            Stock = 999
                        },
                        new
                        {
                            Id = 16,
                            Cost = 15,
                            Description = "[소모품] 신비한 물을 한 모금 마시자 막혔던 뇌의 신경 회로 연산이 뚫리며 총명해집니다. (지능 +10)",
                            ItemType = "Consume",
                            Name = "무안단물",
                            PlusStat = "INT",
                            PlusStatValue = 10,
                            Stock = 999
                        },
                        new
                        {
                            Id = 17,
                            Cost = 10,
                            Description = "[소모품] 긍정적인 마음으로 한 번 크게 웃으면 쉘터 안에 긍정적인 파동과 운이 찾아옵니다. (행운 +10)",
                            ItemType = "Consume",
                            Name = "웃음",
                            PlusStat = "LUK",
                            PlusStatValue = 10,
                            Stock = 999
                        });
                });

            modelBuilder.Entity("TodoRPG.Api.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsCompleted", "CreatedAt");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.Character", b =>
                {
                    b.HasOne("TodoRPG.Api.Models.Dungeon", "CurrentDungeon")
                        .WithMany()
                        .HasForeignKey("CurrentDungeonIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoRPG.Api.Models.User", "User")
                        .WithOne("Character")
                        .HasForeignKey("TodoRPG.Api.Models.Character", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentDungeon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.Inventory", b =>
                {
                    b.HasOne("TodoRPG.Api.Models.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoRPG.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.TodoItem", b =>
                {
                    b.HasOne("TodoRPG.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoRPG.Api.Models.User", b =>
                {
                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
